### PR TITLE
Update on poi libs version

### PR DESCRIPTION
**Pull request by tiagotcsilva**
The poi libs version were very outdated causing conflict problems with other project dependencies.

### CODE REVIEW

**Comment by nigelcharman** [comment]
@robmoffat are you happy for us to pull and release these changes?

**Comment by robmoffat** [comment]
Hi @nigelcharman,

Seeing some failures on the GitHub actions - is it worth trying to fix these first?

**Comment by tiagotcsilva** [comment]
Hi @robmoffat i can fix the errors, i just dont know if i got permission to run the Github actions again

**Comment by robmoffat** [comment]
Hi @tiagotcsilva,
do you want to have a go at fixing the actions?  Feel free to move to a newer JDK - I expect concordion has a minimum JDK number they’re supporting, though.  

I’ll run the actions for you if you comment again on this PR.  I’m away from my desk but I’ll see the email.  Cheers

**Comment by tiagotcsilva** [comment]
Hi @robmoffat i just upgraded gradle version to 8.5, removed jdk 1.8 compilation and added jdk17.

I executed the actions on my fork and it seems ok.

**Comment by nigelcharman** [comment]
@tiagotcsilva thanks for making these changes. It looks like we'll need to make a few changes to the publishing mechanism to release it. Are you OK to wait until after the new year for an official release?

**Comment by tiagotcsilva** [comment]
@nigelcharman it's ok, no problem.

**Pull request merged**
