### PR TITLE
add location information in exceptions and html output

### LINKED ISSUE #15: exceptions during html translation should include location in the excel source
In the current implementation, an error occurs during translation from excel to html/concordion occurs an exception is thrown and displayed to the user as diagnosis.

As the text does not contain any hint to the location of the source of the error, it makes it very difficult do diagnose.

Suggest to include the excel location of the cell being processed with the exception.

### PR DESCRIPTION
**Pull request by vgheo**
fix #15

### CODE REVIEW

**Comment by vgheo** [comment]
Sample output from tutorial 
```
<body>
	<h1>FirstExcelTutorial.xlsx</h1>
	<div excel-location="Taxi Fare Examples" class="example">
		<h2>Taxi Fare Examples</h2>
		<p>
			<span excel-location="A1">Taxi Fare Calculator</span>
		</p>
		<p>
			<span excel-location="A3">Flat Rate</span> <span excel-location="B3"
				concordion:set="#flatRate">£1.00</span>
		</p>

```

**Comment by vgheo** [comment]
Any preference for the new attribute name ?

**Comment by robmoffat** [comment]
Great work!

**Comment by robmoffat** [comment]
Will do a build now and get version 2.1.3 into maven central

**Comment by robmoffat** [comment]
done

**Comment by vgheo** [comment]
I cannot see it in mavencentral. Can you please have a look ?
https://mvnrepository.com/artifact/org.concordion/concordion-excel-extension

**Comment by robmoffat** [comment]
I can see it here: 

https://search.maven.org/search?q=concordion-excel-extension

**Comment by robmoffat** [comment]
Maybe it takes longer for the other one to re-index?

**Comment by vgheo** [comment]
now it is visible at both locations.
thanks!

**Pull request merged**
