### PR TITLE
apache POI library upgraded

### PR DESCRIPTION
**Pull request by wilczelyko**
Upgrade of Apache POI library as old version contained serious known vulnerabilities.

### CODE REVIEW

**Comment by robmoffat** [comment]
I checked out your code - I see the problem you're referring to.

My feeling is that this is something we need to fix in the test. I.e setting the Locale of Java at the start of the test to ensure we get a consistent response.  

I am running in en_GB locale, and it might be best to just fix this at the start of the test:

**AbstractSpecTest:**

```
static {
		Locale.setDefault(Locale.UK);
		ExcelExtension.setConversionMap(conversions);
	}
```

However, even I still have a problem where `true` has now turned to `TRUE` and I think this might be due to using a later JDK.

Possibly best if we just update the expectation for that?

What do you think?

**Comment by wilczelyko** [comment]
Agreed. Fixed as you advised and also replaced currency symbols with codes (only in input) - it also gave me problems (same behaviour as with previous version of apache POI).

**Comment by robmoffat** [comment]
I've merged your changes- I think v2.1.2 of c.e.e. should sync with maven central within the day.

**Comment by wilczelyko** [comment]
Thx

**Pull request merged**
